version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 381492102179.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=381492102179.dkr.ecr.us-east-1.amazonaws.com/demo-ecs-service-image
      - echo $REPOSITORY_URI
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t demo-ecs-service-image .
      - docker tag demo-ecs-service-image:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"demo-ecs-service-container","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
